version = 1

[merge]
automerge_label = "pr:automerge"
require_automerge_label = true
blocking_labels = ["blocked", "pr:on hold", "pr:wip"]
method = "squash"
delete_branch_on_merge = true
optimistic_updates = true
prioritize_ready_to_merge = true
notify_on_conflict = false

[update]
# https://kodiakhq.com/docs/config-reference#updatealways
always = true
# https://kodiakhq.com/docs/config-reference#updateautoupdate_label
autoupdate_label = "pr:autoupdate"

[merge.message]
title = "pull_request_title"
include_coauthors = true
include_pr_number = true
body_type = "markdown"
strip_html_comments = true
