# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'dev'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'dev'

  - package-ecosystem: 'npm'
    directory: '/apps/web-client'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20

  - package-ecosystem: 'npm'
    directory: '/apps/website'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20

  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20

  - package-ecosystem: 'npm'
    directory: '/libs/api-client'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20

  - package-ecosystem: 'npm'
    directory: '/libs/tailwind-config'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20

  - package-ecosystem: 'npm'
    directory: '/libs/ui'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20
