api:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\napi\\n"
apps:internal-docs:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\ninternal-docs\\n"
apps:website:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\nwebsite\\n"
apps:web-client:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\nweb-client\\n"
libs:@odnlabs/api-client:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/api-client\\n"
libs:@odnlabs/tailwind-config:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/tailwind-config\\n"

libs:@odnlabs/ui:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/ui\\n"
libs:@odnlabs/utils-server:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/utils-server\\n"
libs:@odnlabs/utils-client:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/utils-client\\n"
