apps:api:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\napi\\n"
apps:internal:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\ninternal\\n"
apps:site:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\nsite\\n"
apps:web:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\nweb\\n"
libs:@odnlabs/api-client:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/api-client\\n"
libs:eslint-config-odn:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\neslint-config-odn\\n"
libs:@odnlabs/nx-rust:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/nx-rust\\n"
libs:@odnlabs/tailwind-config:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/tailwind-config\\n"
libs:@odnlabs/tsconfig:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/tsconfig\\n"
libs:@odnlabs/ui:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/ui\\n"
libs:@odnlabs/utils:
  - "### Which (application|library|application or library) is this (bug
    report|feature request) for\\?\\n\\n@odnlabs/utils\\n"
