- name: apps:api
  color: fbca04
- name: apps:internal
  color: fbca04
- name: apps:site
  color: fbca04
- name: apps:web
  color: fbca04
- name: backlog
  color: 7ef7ef
- name: backport
  color: 88aabb
- name: blocked
  color: fc1423
- name: bug
  color: d73a4a
- name: chore
  color: ffffff
- name: ci
  color: 0075ca
- name: dependencies
  color: 276bd1
- name: discussion
  color: b6b1f9
- name: documentation
  color: 0075ca
- name: duplicate
  color: cfd3d7
- name: error handling
  color: 80c042
- name: feature request
  color: fcf95a
- name: good first issue
  color: 7057ff
- name: has PR
  color: 4b1f8e
- name: help wanted
  color: '008672'
- name: in progress
  color: ffccd7
- name: in review
  color: aed5fc
- name: invalid
  color: e4e669
- name: packages:api-client
  color: fbca04
- name: packages:eslint-config-odn
  color: fbca04
- name: packages:tailwind-config
  color: fbca04
- name: packages:tsconfig
  color: fbca04
- name: packages:ui
  color: fbca04
- name: packages:utils
  color: fbca04
- name: performance
  color: 80c042
- name: priority:high
  color: fc1423
- name: refactor
  color: 1d637f
- name: regression
  color: ea8785
- name: sharding
  color: 80c042
- name: tests
  color: f06dff
- name: typings
  color: 80c042
- name: utility
  color: 80c042
- name: wontfix
  color: ffffff
