version: '3.3'
services:
  api:
    build: ./api
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: production
    ports:
      - '5000:5000'
    networks:
      - app-network

  site:
    build: ./site
    env_file:
      - ./site/.env.local
    environment:
      NEXT_PUBLIC_APP_NODE_ENV: production
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

  web:
    build: ./web
    env_file:
      - ./web/.env.local
    environment:
      NEXT_PUBLIC_APP_NODE_ENV: production
    ports:
      - '3500:3500'
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/:/etc/ssl/:ro
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - api
      - site
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
