version: '3'
services:
  site:
    container_name: site
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.site
      args:
        DOCKER_BUILDKIT: 1
    env_file:
      - .env.production
    restart: always
    ports:
      - '4000:4000'
    networks:
      - app-network

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.web
      args:
        DOCKER_BUILDKIT: 1
    env_file:
      - .env.production
    restart: always
    ports:
      - '4100:4100'
    networks:
      - app-network

  internal:
    container_name: internal
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.internal
      args:
        DOCKER_BUILDKIT: 1
    env_file:
      - .env.production
    restart: always
    ports:
      - '4100:4100'
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./docker/development/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    depends_on:
      - site
      - web
      - internal
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
