networks:
  app-network:
    driver: bridge
services:
  api:
    build:
      args:
        DOCKER_BUILDKIT: 1
      context: .
      dockerfile: ./docker/production/Dockerfile.api
    container_name: api
    depends_on:
      - postgres
    env_file:
      - .env.production
    networks:
      - app-network
    ports:
      - '5000:5000'
    restart: always
  internal_docs:
    build:
      args:
        DOCKER_BUILDKIT: 1
      context: .
      dockerfile: ./docker/production/Dockerfile.internal_docs
    container_name: internal_docs
    env_file:
      - .env.production
    networks:
      - app-network
    ports:
      - '4200:4200'
    restart: always
  postgres:
    container_name: postgres
    env_file:
      - .env.production
    image: postgres:latest
    ports:
      - '6500:5432'
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
  web_client:
    build:
      args:
        DOCKER_BUILDKIT: 1
      context: .
      dockerfile: ./docker/production/Dockerfile.web_client
    container_name: web_client
    env_file:
      - .env.production
    networks:
      - app-network
    ports:
      - '4100:4100'
    restart: always
  website:
    build:
      args:
        DOCKER_BUILDKIT: 1
      context: .
      dockerfile: ./docker/production/Dockerfile.website
    container_name: website
    env_file:
      - .env.production
    networks:
      - app-network
    ports:
      - '4000:4000'
    restart: always
version: '3'
