version: '3'
services:
  website:
    container_name: website
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.website
      args:
        DOCKER_BUILDKIT: 1
    env_file:
      - .env.production
    restart: always
    ports:
      - '4000:4000'
    networks:
      - app-network

  web_client:
    container_name: web_client
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.web_client
      args:
        DOCKER_BUILDKIT: 1
    env_file:
      - .env.production
    restart: always
    ports:
      - '4100:4100'
    networks:
      - app-network

  internal_docs:
    container_name: internal_docs
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.internal_docs
      args:
        DOCKER_BUILDKIT: 1
    env_file:
      - .env.production
    restart: always
    ports:
      - '4200:4200'
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./docker/development/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    depends_on:
      - website
      - web_client
      - internal_docs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
