# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: setup node env
description: Setup node.js environment with pnpm
runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
        check-latest: true

    - name: Install dependencies
      shell: bash
      uses: ./tools/actions/pnpm-install

    - name: Create Environment Variables
      shell: bash
      run: |
        chmod +x run.sh &&
        ./run.sh ci setup env
