# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json
extends:
  - 'slekup/next'
ignorePatterns:
  - 'tailwind.config.ts'
parserOptions:
  project:
    - './apps/web-client/tsconfig.json'
