# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Bug report
description: Report an issue with Open Dev Net or one of its libraries.
labels: [bug, need repro]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing an issue!
  - type: dropdown
    id: package
    attributes:
      label: Which repo is this bug report for?
      options:
        - None (general issue)
        - API
        - Website
        - Web client
        - Other (specify below)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: Describe the issue in as much detail as possible.
      placeholder: |
        Steps to reproduce with below code sample:
        1. Do thing
        2. Observe behavior
        3. See error logs below
    validations:
      required: true
  - type: textarea
    id: code_sample
    attributes:
      label: Code sample
      description: |
        Your code sample should be:
        1. Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        2. Complete - Provide all parts someone else needs to reproduce your problem
        3. Reproducible - Test the code you're about to provide to make sure it reproduces the problem

        This will be automatically formatted into code, so no need for backticks.
      render: TypeScript
  - type: dropdown
    id: priority
    attributes:
      label: Issue priority
      description: Please be realistic. If you need to elaborate on your reasoning, please use the issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
