# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: GitHub Discussion
    url: https://github.com/orgs/odnlabs/discussions
    about: Ask questions and get direct support in our discussion forum.
