version: '3.3'

services:
  api:
    build:
      context: ../../
      dockerfile: ./docker/production/Dockerfile.api
    container_name: api
    env_file:
      - ../../.env.production
    networks:
      - app-network
    ports:
      - '5000:5000'
    restart: always

  internal_docs:
    container_name: internal_docs
    depends_on:
      - api
    env_file:
      - ../../.env.production
    environment:
      NEXT_PUBLIC_APP_NODE_ENV: production
    image: slekup/opendevnet-internal_docs:main
    networks:
      - app-network
    ports:
      - '4200:4200'
    restart: always

  web_client:
    container_name: web
    depends_on:
      - api
    env_file:
      - ../../.env.production
    image: slekup/opendevnet-web_client:main
    networks:
      - app-network
    ports:
      - '4100:4100'
    restart: always

  website:
    container_name: website
    depends_on:
      - api
    env_file:
      - ../../.env.production
    environment:
      NEXT_PUBLIC_APP_NODE_ENV: production
    image: slekup/opendevnet-website:main
    networks:
      - app-network
    ports:
      - '4000:4000'
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - api
      - website
      - web_client
      - internal_docs
    image: nginx:latest
    networks:
      - app-network
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/:/etc/ssl/:ro

networks:
  app-network:
    driver: bridge
