version: '3'
services:
  postgres:
    container_name: postgres
    env_file:
      - ../../.env.ci
    image: postgres:latest
    ports:
      - '6500:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ../../
      dockerfile: ./docker/ci/Dockerfile.api
    container_name: api
    depends_on:
      - postgres
    env_file:
      - ../../.env.ci
    networks:
      - app-network
    ports:
      - '5000:5000'
    restart: always

  internal_docs:
    build:
      context: ../../
      dockerfile: ./docker/ci/Dockerfile.internal_docs
    container_name: internal_docs
    env_file:
      - ../../.env.ci
    networks:
      - app-network
    ports:
      - '4200:4200'
    restart: always

  web_client:
    build:
      context: ../../
      dockerfile: ./docker/ci/Dockerfile.web_client
    container_name: web_client
    env_file:
      - ../../.env.ci
    networks:
      - app-network
    ports:
      - '4100:4100'
    restart: always

  website:
    build:
      context: ../../
      dockerfile: ./docker/ci/Dockerfile.website
    container_name: website
    env_file:
      - ../../.env.ci
    networks:
      - app-network
    ports:
      - '4000:4000'
    restart: always

networks:
  app-network:
    driver: bridge
