name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker images
        run: |
          touch .env.local
          docker-compose -f docker-compose.testing.yml build --no-cache --force-rm

  test:
    name: Test Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test the Docker image
        run: |
          touch .env.local
          docker-compose -f docker-compose.testing.yml up -d --build

  push_site_to_registry:
    name: Publish Site to Docker Hub
    runs-on: ubuntu-latest
    needs: ['build', 'test']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta_api
        uses: docker/metadata-action@v4
        with:
          images: docker.io/slekup/opendevnet-site

      - name: Publish Site
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/production/Dockerfile.site
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
          platforms: linux/amd64,linux/arm64

  push_web_to_registry:
    name: Publish Web to Docker Hub
    runs-on: ubuntu-latest
    needs: ['build', 'test']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta_web
        uses: docker/metadata-action@v4
        with:
          images: docker.io/slekup/opendevnet-web

      - name: Publish Web App
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/production/Dockerfile.web
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}
          platforms: linux/amd64,linux/arm64

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: ['push_site_to_registry', 'push_web_to_registry']
    steps:
      - name: Install SSH Keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Connect and Deploy
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && chmod +x run.sh && ./run.sh prod update && exit"
      - name: Cleanup
        run: rm -rf ~/.ssh
