# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Issue Labeler

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  issue-labeler:
    name: Issue Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue Labeler
        uses: github/issue-labeler@v3.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
