# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Labeler

on: pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-labeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run Labeler
        uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
          configuration-path: .github/labeler.yaml
